FROM python:3.11.4-slim-bullseye
ARG POETRY_HOME=/etc/poetry
WORKDIR /home/bbn

RUN apt update && apt install -y curl git
RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=${POETRY_HOME} python3 -

ENV PATH ${POETRY_HOME}/bin:$PATH

CMD ["/bin/bash"]
